version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cloudapp2026
      POSTGRES_DB: cloudapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloudapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth:
    build: ./services/auth
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://postgres:cloudapp2026@postgres:5432/cloudapp_db
      SECRET_KEY: cloudapp_jwt_secret_2026
    volumes:
      - ./services/shared:/app/shared
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cloudapp-network

  project:
    build: ./services/project
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://postgres:cloudapp2026@postgres:5432/cloudapp_db
    volumes:
      - ./services/shared:/app/shared
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cloudapp-network

  billing:
    build: ./services/billing
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: postgresql://postgres:cloudapp2026@postgres:5432/cloudapp_db
    volumes:
      - ./services/shared:/app/shared
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cloudapp-network

  notification:
    build: ./services/notification
    ports:
      - "8004:8004"
    environment:
      RESEND_API_KEY: re_eAaHN2mR_4iNW4nMchNcws4kpchFcmh96
      DATABASE_URL: postgresql://postgres:cloudapp2026@postgres:5432/cloudapp_db
    volumes:
      - ./services/shared:/app/shared
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cloudapp-network

  analytics:
    build: ./services/analytics
    ports:
      - "8005:8005"
    environment:
      DATABASE_URL: postgresql://postgres:cloudapp2026@postgres:5432/cloudapp_db
    volumes:
      - ./services/shared:/app/shared
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cloudapp-network

  gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    volumes:
      - ./services/shared:/app/shared
    depends_on:
      - auth
      - project
      - billing
      - notification
      - analytics
    networks:
      - cloudapp-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - cloudapp-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cloudapp-network
    depends_on:
      - gateway

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: cloudapp2026
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - cloudapp-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:

networks:
  cloudapp-network:
    driver: bridge